kind: PersistentVolume
apiVersion: v1
metadata:
  name: elastic-pv-volume
  labels:
    type: local
    app: elastic
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /Data/Elastic
    type: DirectoryOrCreate