kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elastic-pv-claim
  labels:
    app: elastic
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi