kind: PersistentVolume
apiVersion: v1
metadata:
  name: elastic-mongo-db-pv-volume
  labels:
    type: local
    app: elastic-mongo-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /Data/ElasticMongoDB
    type: DirectoryOrCreate