kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elastic-mongo-db-pv-claim
  labels:
    app: elastic-mongo-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi