apiVersion: v1
kind: Service
metadata:
  name: elastic-mongo-db-service
  labels:
    app: elastic-mongo-db
spec:
  type: NodePort
  ports:
    - port: 20500
      targetPort: 27017
  selector:
    app: elastic-mongo-db