apiVersion: v1
kind: Service
metadata:
  name: user-service-db-exporter-service
  labels:
    app: user-service-db-exporter
spec:
  type: NodePort
  ports:
    - name: db-traffic
      port: 20500
      targetPort: 9187
  selector:
    app: user-service-db-exporter