apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-db-config
  labels:
    app: user-service-db
data:
  POSTGRES_USER: userservice
  POSTGRES_PASSWORD: userservicepass

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-db-config-maxcons
  labels:
    app: user-service-db
data:
  max_conns.sql: "ALTER SYSTEM SET max_connections = 500;"